Create 1st version, add custom checkboxes
VolhaVaitulevich/To-Do-List pull request #1
Opened 2022-12-07 22:59 UTC by VolhaVaitulevich

1. Created the 1st version of the page;
2. Added custom checkboxes;

2022-12-09 20:52 UTC, siarhei-papkou requested changes

2022-12-09 20:52 UTC, siarhei-papkou commented on src/style.scss
> +	-webkit-appearance: none;
redundant. autoprefixer adds it for you.

2022-12-09 20:52 UTC, siarhei-papkou commented on src/style.scss
> +				box-shadow: 0 0 0 2px #5C9DFE, 0 0 0 4px #015ADF;
missed raw values

2022-12-09 20:52 UTC, siarhei-papkou commented on src/style.scss
> +			.check__box {
redundat nesting

2022-12-09 20:52 UTC, siarhei-papkou commented on src/style.scss
> +	margin-left: -30px;
we can use more suitable positioning props

2022-12-09 20:52 UTC, siarhei-papkou commented on src/style.scss
> +	margin: 1% calc(50vw - 325px);
calc(50vw - 325px) => auto

2022-12-11 12:21 UTC, VolhaVaitulevich commented on src/style.scss
> +	margin-left: -30px;
Updated in a new commit

2022-12-11 12:21 UTC, VolhaVaitulevich commented on src/style.scss
> +	margin: 1% calc(50vw - 325px);
I don't understand, should I change this to 'auto'? Because in this case, the block 'content' will take up the whole page

2022-12-11 12:21 UTC, VolhaVaitulevich commented on src/style.scss
> +			.check__box {
Updated in a new commit

2022-12-11 12:22 UTC, VolhaVaitulevich commented on src/style.scss
> +				box-shadow: 0 0 0 2px #5C9DFE, 0 0 0 4px #015ADF;
sorry, I didn't understand what it means, what was missed?

2022-12-11 12:22 UTC, VolhaVaitulevich commented on src/style.scss
> +	-webkit-appearance: none;
Removed in a new commit

2022-12-14 10:12 UTC, siarhei-papkou approved these changes

2022-12-14 10:12 UTC, merged