add 'delete task' functionality
VolhaVaitulevich/To-Do-List pull request #3
Opened 2022-12-29 10:11 UTC by VolhaVaitulevich

2022-12-30 10:38 UTC, siarhei-papkou requested changes

2022-12-30 10:38 UTC, siarhei-papkou commented on src/app/application.ts
> +    const deletedTaskIndex = this.existingTasks.findIndex((item) => item.id === task.id);
filter

2022-12-30 10:38 UTC, siarhei-papkou commented on src/app/application.ts
> +    const completedTaskIndex = this.existingTasks.findIndex((item) => item.id === task.id);
map

2023-01-06 09:09 UTC, siarhei-papkou requested changes

2023-01-06 09:09 UTC, siarhei-papkou commented on src/app/application.ts
> +    this.storage.setTasks(newTasksList);
move to updateTasksList

2023-01-06 09:09 UTC, siarhei-papkou commented on src/app/application.ts
> +    this.storage.setTasks(newTasksList);
move to updateTasksList

2023-01-06 09:09 UTC, siarhei-papkou commented on src/utils/isEqual.ts
> +  console.log(newTasksList);
remove

2023-01-06 09:09 UTC, siarhei-papkou commented on src/utils/isEqual.ts
> +  if (JSON.stringify(existingTasksList) === JSON.stringify(newTasksList)) {
![image](https://user-images.githubusercontent.com/95697276/210968808-7b8e1db0-b797-4ac8-9361-b9c4b8abccca.png)

2023-01-09 22:09 UTC, VolhaVaitulevich commented on src/utils/isEqual.ts
> +  if (JSON.stringify(existingTasksList) === JSON.stringify(newTasksList)) {
Updated in a new commit

2023-01-10 13:44 UTC, siarhei-papkou commented on src/app/application.ts
> +    this.existingTasks = [];
<img width="718" alt="image" src="https://user-images.githubusercontent.com/95697276/211567279-1c911889-58f6-46d0-aa3f-58a6630314bc.png">

2023-01-10 13:46 UTC, siarhei-papkou approved these changes

2023-01-10 15:39 UTC, merged